version: '3.9'
services:
  birdnest-db:
    image: postgres:15.0-alpine
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=birdnest
    ports:
    - '5434:5432'
  birdnest-test-db:
    image: postgres:15.0-alpine
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=birdnest-test
    ports:
    - '5435:5432'